name: Run NUnit Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'  # Replace with the specific version you need

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Change directory and test
      run: |
        cd EmployeeApp/TestClass_EmployeeAPP  # Change to the directory where the csproj file is located
        dotnet test --filter FullyQualifiedName=TestClass_EmployeeAPP.Tests
