name: Run Test Class

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: windows-latest  # Use windows-latest for Windows runners

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.x'  # Replace with your desired version

    - name: Restore dependencies
      run: dotnet restore

    - name: Run specific test class
      run: dotnet test --filter FullyQualifiedName~EmployeeApp.TestClass_EmployeeAPP
